### ISSUE TITLE
Ive got an issue

### ISSUE THREAD

**Issue by TVXR-DanielYT** [useragents/Valorant-Account-Checker-with-Capture#2]
hello i have an issue on the valorant account checker "12/07/2022 18:21:46
list index out of range" this is the error message 

good bye

**Comment by 3219807** [comment]
same I've been getting "list index out of range"

**Comment by useragents** [comment]
Fixed. Download the latest version [here](https://github.com/useragents/Valorant-Account-Checker-with-Capture/archive/refs/heads/main.zip).
